Repository fga-gpp-mds/2018.1-TropicalHazards-BI-FrontEnd, pull requests merged in 2018-05, with the labels that each got.

#65 Issue 52 auth comp test
  .babelrc
  .gitignore
  package-lock.json
  package.json
  src/components/Authentication/Login.vue
  src/components/Authentication/Register.vue
  src/components/Utils/Footer.vue
  src/components/Utils/LandingPage.vue
  src/main.js
  test/e2e/custom-assertions/elementCount.js
  test/e2e/nightwatch.conf.js
  test/e2e/runner.js
  test/e2e/specs/test.js
  test/unit/specs/About.spec.js
  test/unit/specs/CardsContent.spec.js
  test/unit/specs/Footer.spec.js
  test/unit/specs/LandingPage.spec.js
  test/unit/specs/Login.spec.js
  test/unit/specs/Navbar.spec.js
  test/unit/specs/Register.spec.js
  test/unit/specs/SecondNavbar.spec.js
  test/unit/specs/Sidebar.spec.js
Labels: TS, help wanted, test

#82 Issue 68 csv data filter
  package-lock.json
  package.json
  src/components/Files/DefineData.vue
  src/components/Files/FilterCsv.vue
  src/components/Files/ImportCsv.vue
  src/components/Files/SendData.vue
  src/components/Projects/ProjectDetail.vue
Labels: MDS, front-end

#80 Issue 70 filter projects by tag
  src/components/Users/HomePage.vue
Labels: Debts, MDS, enhancement, work in progress

#83 Issue 290 environment variables
  .travis.yml
  Dockerfile
  Dockerfile.dev
  Dockerfile.prod
  Dockerfile.test
  README.md
  config/dev.env.js
  config/index.js
  config/prod.env.js
  docker-compose.dev.yml
  docker-compose.test.yml
  docker-compose.yml
  package.json
  src/main.js
  start-prod.sh
  start.sh
Labels: EPS, dev-ops, enhancement

#91 semantic-release configurations
  .travis.yml
  package-lock.json
  package.json
Labels: pending review

#98 Issue 90 resolve errors de jquery
  .eslintrc.js
  src/components/Observatorio/ObservatorioDetail.vue
  src/components/Observatorio/createObservatorio.vue
  src/components/Observatorio/modalDeleteObservatorio.vue
  src/components/Projects/CreateProject.vue
  src/components/Projects/CreateTag.vue
  src/components/Users/DeleteUser.vue
  src/components/Users/EditUser.vue
  src/components/Users/HomePage.vue
  src/components/Utils/Navbar.vue
Labels: Not planned, bug, pending review

#99 [HOTFIX] fix travis deploy pipeline to rancher
  .travis.yml
  semantic-release.sh
  travis-deploy.sh
Labels: EPS, bug, dev-ops, hotfix

#108 Issue 104 sentry setup and docker volume fix
  Dockerfile
  docker-compose.test.yml
  docker-compose.yml
  package-lock.json
  package.json
  semantic-release.sh
  src/main.js
  start.sh
Labels: EPS, bug, dev-ops, enhancement, front-end, hotfix
