Repository fga-gpp-mds/2018.1-TropicalHazards-BI-FrontEnd, pull requests merged in 2018-04, with the labels that each got.

#11 Issue 2 development enviroment front
  Dockerfile
  README.md
  build/webpack.dev.conf.js
  docker-compose.yml
  package-lock.json
  package.json
Labels: Planned, enhancement, pending review

#13 add docker development environment
  Dockerfile
  README.md
  build/webpack.dev.conf.js
  docker-compose.yml
  package-lock.json
  package.json
Labels: EPS, easy, front-end, pending review

#36 Issue 32 problem routes
  src/components/Projects/ListProject.vue
  src/components/Utils/Navbar.vue
Labels: MDS, bug, easy

#45 Issue 41 about text
  .travis.yml
  index.html
  src/components/Authentication/Login.vue
  src/components/Authentication/Register.vue
  src/components/Modals/modal.vue
  src/components/Modals/modalDeleteProject.vue
  src/components/Modals/modalEditUser.vue
  src/components/Modals/modalNewProject.vue
  src/components/Modals/modalRegister.vue
  src/components/Observatorio/ObservatorioDetail.vue
  src/components/Projects/CreateProject.vue
  src/components/Projects/EditProject.vue
  src/components/Projects/ListProject.vue
  src/components/Projects/ProjectDetail.vue
  src/components/Projects/modalDeleteProject.vue
  src/components/Projects/modalNewProject.vue
  src/components/Users/CreateUser.vue
  src/components/Users/DeleteUser.vue
  src/components/Users/EditUser.vue
  src/components/Users/HomePage.vue
  src/components/Users/modal.vue
  src/components/Users/modalEditUser.vue
  src/components/Users/modalRegister.vue
  src/components/Utils/Navbar.vue
  src/components/Utils/SecondNavBar.vue
  src/components/Utils/SideBar.vue
  src/main.js
Labels: MDS, bug, easy

#55 [ADD] add create observatory
  src/components/Observatorio/createObservatorio.vue
  src/components/Projects/ProjectDetail.vue
  src/router/index.js
Labels: MDS, easy, front-end

#62 [UPDATE] update animations to transitions components
  src/App.vue
Labels: MDS, easy, front-end

#58 Issue 48 delete dashboard
  src/components/Observatorio/ObservatorioDetail.vue
  src/components/Observatorio/editObservatorio.vue
  src/components/Projects/ProjectDetail.vue
  src/components/Users/HomePage.vue
  src/router/index.js
Labels: MDS, easy, front-end, pending review

#57 Issue 50 edit dashboard
  src/components/Observatorio/editObservatorio.vue
  src/components/Projects/ProjectDetail.vue
  src/components/Users/HomePage.vue
  src/router/index.js
Labels: Debts, Important, MDS, front-end, pending review
