Repository fga-gpp-mds/2018.1-TropicalHazards-BI-FrontEnd, pull requests merged in 2018-06, with the labels that each got.

#129 Issue 117 navigation guard
  src/components/Auth/LoginForm.vue
  src/components/Auth/middleware.js
  src/components/Modals/modalLogin.vue
  src/components/Utils/SideBar.vue
  src/router/index.js
  src/store/Authentication/auth.js
Labels: MDS, front-end

#153 solves #150
  src/components/Landing/Navbar.vue
Labels: Important, Planned, pending review

#155 [FIX] fix some bugs describle on issue
  src/components/Landing/Navbar.vue
  src/components/Projects/MyProjects.vue
  src/components/Utils/SideBar.vue
Labels: MDS, pending review

#141 WIP: Project detail and edit project
  src/components/Dashboards/DashboardDetail.vue
  src/components/Dashboards/createDashboard.vue
  src/components/Dashboards/editDashboard.vue
  src/components/FileUpload/InsertFile.vue
  src/components/Projects/CreateProject.vue
  src/components/Projects/EditProject.vue
  src/components/Projects/MyProjects.vue
  src/components/Projects/ProjectDetail.vue
  src/components/Projects/ProjectForm.vue
  src/components/Tags/CreateTag.vue
  src/components/Users/EditUser.vue
  src/components/Users/HomePage.vue
  src/components/Utils/Footer.vue
  src/components/Utils/Sidebar.vue
  src/components/styles/base.scss
  src/router/index.js
  src/store/Projects/Project.js
  test/unit/specs/Sidebar.spec.js
Labels: work in progress

#157 [UPDATE] update feedback to user fail in register and router-link whe…
  src/components/Auth/LoginForm.vue
  src/components/Auth/RegisterForm.vue
  src/components/Landing/Navbar.vue
  src/store/Authentication/auth.js
Labels: Important, MDS, bug

#152 WIP: Issue 95 results
  src/App.vue
  src/components/Dashboards/DashboardDetail.vue
  src/components/Dashboards/modalDeleteObservatorio.vue
  src/components/FileUpload/InsertFile.vue
  src/components/Files/DefineData.vue
  src/components/Files/Filter.vue
  src/components/Files/FilterCsv.vue
  src/components/Files/SendData.vue
  src/components/Landing/Header.vue
  src/components/Modals/modalLogin.vue
  src/components/Modals/modalRegister.vue
  src/components/Projects/MyProjects.vue
  src/components/Projects/ProjectDetail.vue
  src/components/Projects/ProjectsList.vue
  src/components/Questions/IframeComponent.vue
  src/components/Tags/CreateTag.vue
  src/components/Users/DeleteUser.vue
  src/components/Users/EditUser.vue
  src/components/Utils/CardsContent.vue
  src/components/Utils/SecondNavBar.vue
  src/components/Utils/Sidebar.vue
  src/components/styles/base.scss
  src/router/index.js
  src/store/Projects/Project.js
Labels: MDS, Planned, Too Important, UI/UX, enhancement, front-end, pending review

#165 WIP Responsive sidebar
  src/components/Dashboards/CreateDashboard.vue
  src/components/Dashboards/EditDashboard.vue
  src/components/Projects/MyProjects.vue
  src/components/Projects/ProjectsList.vue
  src/components/Users/HomePage.vue
  src/components/Users/HomePageDefault.vue
  src/components/styles/base.scss
  src/router/index.js
Labels: work in progress

#178 Issue 177 fix questions
  src/components/Dashboards/DashboardDetail.vue
  src/components/Questions/AddFilter.vue
  src/components/Questions/AskQuestion.vue
  src/components/Questions/QueryComponent.vue
  src/store/Projects/Project.js
Labels: Too Important, help wanted

#175 [ADD] add b-alert message to import
  src/components/Files/ContainerImport.vue
  src/components/Files/SendData.vue
  src/components/Users/HomePageDefault.vue
Labels: MDS, pending review
